### ISSUE TITLE
Fix failed to initiate new environment

### ISSUE THREAD

**Issue by ahmad-abbad** [Vardot/platformsh-varbase10x00#14]
### Describe the bug

error message 
 15 packages are looking for funding
      run `npm fund` for details
    W: 
  
  Executing build hook...
    
    Fatal error: Declaration of Composer\Command\InitCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /app/.global/composer/composer/vendor/composer/composer/src/Composer/Command/InitCommand.php on line 85
    W: PHP Fatal error:  Declaration of Composer\Command\InitCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /app/.global/composer/composer/vendor/composer/composer/src/Composer/Command/InitCommand.php on line 85
  
  E: Error building project: Step failed with status code 255.

E: Error: Unable to build application, aborting.

### Include some logs

error message 
 15 packages are looking for funding
      run `npm fund` for details
    W: 
  
  Executing build hook...
    
    Fatal error: Declaration of Composer\Command\InitCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /app/.global/composer/composer/vendor/composer/composer/src/Composer/Command/InitCommand.php on line 85
    W: PHP Fatal error:  Declaration of Composer\Command\InitCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /app/.global/composer/composer/vendor/composer/composer/src/Composer/Command/InitCommand.php on line 85
  
  E: Error building project: Step failed with status code 255.

E: Error: Unable to build application, aborting.

### Reproducing

- install Varbase 10 with PSH

### Expected behavior

- Fix composer version
https://github.com/composer/composer/issues/11736

### Your environment

dev

**Comment by Natshah** [comment]
Agreed on the quick fix for this as listed from the info
https://v8.dev/blog/math-random

**Comment by Natshah** [comment]
This is a **TEMP** quick merge for the pull request.
Until platformsh let us upgrade to latest composer version.
